// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/protos/publication-stats.proto

package org.nextprot.stats.publication;

public final class PublicationStatistics {
  private PublicationStatistics() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PublicationStatsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:nextprot.PublicationStats)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 id = 1;</code>
     */
    long getId();

    /**
     * <code>bool is_cited = 2;</code>
     */
    boolean getIsCited();

    /**
     * <code>bool is_large_scale = 3;</code>
     */
    boolean getIsLargeScale();

    /**
     * <code>bool is_curated = 4;</code>
     */
    boolean getIsCurated();

    /**
     * <code>bool is_computed = 5;</code>
     */
    boolean getIsComputed();
  }
  /**
   * Protobuf type {@code nextprot.PublicationStats}
   */
  public  static final class PublicationStats extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:nextprot.PublicationStats)
      PublicationStatsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PublicationStats.newBuilder() to construct.
    private PublicationStats(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PublicationStats() {
      id_ = 0L;
      isCited_ = false;
      isLargeScale_ = false;
      isCurated_ = false;
      isComputed_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PublicationStats(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt64();
              break;
            }
            case 16: {

              isCited_ = input.readBool();
              break;
            }
            case 24: {

              isLargeScale_ = input.readBool();
              break;
            }
            case 32: {

              isCurated_ = input.readBool();
              break;
            }
            case 40: {

              isComputed_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.nextprot.stats.publication.PublicationStatistics.internal_static_nextprot_PublicationStats_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.nextprot.stats.publication.PublicationStatistics.internal_static_nextprot_PublicationStats_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.nextprot.stats.publication.PublicationStatistics.PublicationStats.class, org.nextprot.stats.publication.PublicationStatistics.PublicationStats.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    public static final int IS_CITED_FIELD_NUMBER = 2;
    private boolean isCited_;
    /**
     * <code>bool is_cited = 2;</code>
     */
    public boolean getIsCited() {
      return isCited_;
    }

    public static final int IS_LARGE_SCALE_FIELD_NUMBER = 3;
    private boolean isLargeScale_;
    /**
     * <code>bool is_large_scale = 3;</code>
     */
    public boolean getIsLargeScale() {
      return isLargeScale_;
    }

    public static final int IS_CURATED_FIELD_NUMBER = 4;
    private boolean isCurated_;
    /**
     * <code>bool is_curated = 4;</code>
     */
    public boolean getIsCurated() {
      return isCurated_;
    }

    public static final int IS_COMPUTED_FIELD_NUMBER = 5;
    private boolean isComputed_;
    /**
     * <code>bool is_computed = 5;</code>
     */
    public boolean getIsComputed() {
      return isComputed_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      if (isCited_ != false) {
        output.writeBool(2, isCited_);
      }
      if (isLargeScale_ != false) {
        output.writeBool(3, isLargeScale_);
      }
      if (isCurated_ != false) {
        output.writeBool(4, isCurated_);
      }
      if (isComputed_ != false) {
        output.writeBool(5, isComputed_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (isCited_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, isCited_);
      }
      if (isLargeScale_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, isLargeScale_);
      }
      if (isCurated_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, isCurated_);
      }
      if (isComputed_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, isComputed_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.nextprot.stats.publication.PublicationStatistics.PublicationStats)) {
        return super.equals(obj);
      }
      org.nextprot.stats.publication.PublicationStatistics.PublicationStats other = (org.nextprot.stats.publication.PublicationStatistics.PublicationStats) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && (getIsCited()
          == other.getIsCited());
      result = result && (getIsLargeScale()
          == other.getIsLargeScale());
      result = result && (getIsCurated()
          == other.getIsCurated());
      result = result && (getIsComputed()
          == other.getIsComputed());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + IS_CITED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsCited());
      hash = (37 * hash) + IS_LARGE_SCALE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsLargeScale());
      hash = (37 * hash) + IS_CURATED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsCurated());
      hash = (37 * hash) + IS_COMPUTED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsComputed());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.nextprot.stats.publication.PublicationStatistics.PublicationStats parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.nextprot.stats.publication.PublicationStatistics.PublicationStats parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.nextprot.stats.publication.PublicationStatistics.PublicationStats parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.nextprot.stats.publication.PublicationStatistics.PublicationStats parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.nextprot.stats.publication.PublicationStatistics.PublicationStats parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.nextprot.stats.publication.PublicationStatistics.PublicationStats parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.nextprot.stats.publication.PublicationStatistics.PublicationStats parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.nextprot.stats.publication.PublicationStatistics.PublicationStats parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.nextprot.stats.publication.PublicationStatistics.PublicationStats parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.nextprot.stats.publication.PublicationStatistics.PublicationStats parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.nextprot.stats.publication.PublicationStatistics.PublicationStats parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.nextprot.stats.publication.PublicationStatistics.PublicationStats parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.nextprot.stats.publication.PublicationStatistics.PublicationStats prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code nextprot.PublicationStats}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:nextprot.PublicationStats)
        org.nextprot.stats.publication.PublicationStatistics.PublicationStatsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.nextprot.stats.publication.PublicationStatistics.internal_static_nextprot_PublicationStats_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.nextprot.stats.publication.PublicationStatistics.internal_static_nextprot_PublicationStats_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.nextprot.stats.publication.PublicationStatistics.PublicationStats.class, org.nextprot.stats.publication.PublicationStatistics.PublicationStats.Builder.class);
      }

      // Construct using org.nextprot.stats.publication.PublicationStatistics.PublicationStats.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0L;

        isCited_ = false;

        isLargeScale_ = false;

        isCurated_ = false;

        isComputed_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.nextprot.stats.publication.PublicationStatistics.internal_static_nextprot_PublicationStats_descriptor;
      }

      @java.lang.Override
      public org.nextprot.stats.publication.PublicationStatistics.PublicationStats getDefaultInstanceForType() {
        return org.nextprot.stats.publication.PublicationStatistics.PublicationStats.getDefaultInstance();
      }

      @java.lang.Override
      public org.nextprot.stats.publication.PublicationStatistics.PublicationStats build() {
        org.nextprot.stats.publication.PublicationStatistics.PublicationStats result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.nextprot.stats.publication.PublicationStatistics.PublicationStats buildPartial() {
        org.nextprot.stats.publication.PublicationStatistics.PublicationStats result = new org.nextprot.stats.publication.PublicationStatistics.PublicationStats(this);
        result.id_ = id_;
        result.isCited_ = isCited_;
        result.isLargeScale_ = isLargeScale_;
        result.isCurated_ = isCurated_;
        result.isComputed_ = isComputed_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.nextprot.stats.publication.PublicationStatistics.PublicationStats) {
          return mergeFrom((org.nextprot.stats.publication.PublicationStatistics.PublicationStats)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.nextprot.stats.publication.PublicationStatistics.PublicationStats other) {
        if (other == org.nextprot.stats.publication.PublicationStatistics.PublicationStats.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (other.getIsCited() != false) {
          setIsCited(other.getIsCited());
        }
        if (other.getIsLargeScale() != false) {
          setIsLargeScale(other.getIsLargeScale());
        }
        if (other.getIsCurated() != false) {
          setIsCurated(other.getIsCurated());
        }
        if (other.getIsComputed() != false) {
          setIsComputed(other.getIsComputed());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.nextprot.stats.publication.PublicationStatistics.PublicationStats parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.nextprot.stats.publication.PublicationStatistics.PublicationStats) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long id_ ;
      /**
       * <code>int64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>int64 id = 1;</code>
       */
      public Builder setId(long value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0L;
        onChanged();
        return this;
      }

      private boolean isCited_ ;
      /**
       * <code>bool is_cited = 2;</code>
       */
      public boolean getIsCited() {
        return isCited_;
      }
      /**
       * <code>bool is_cited = 2;</code>
       */
      public Builder setIsCited(boolean value) {
        
        isCited_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool is_cited = 2;</code>
       */
      public Builder clearIsCited() {
        
        isCited_ = false;
        onChanged();
        return this;
      }

      private boolean isLargeScale_ ;
      /**
       * <code>bool is_large_scale = 3;</code>
       */
      public boolean getIsLargeScale() {
        return isLargeScale_;
      }
      /**
       * <code>bool is_large_scale = 3;</code>
       */
      public Builder setIsLargeScale(boolean value) {
        
        isLargeScale_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool is_large_scale = 3;</code>
       */
      public Builder clearIsLargeScale() {
        
        isLargeScale_ = false;
        onChanged();
        return this;
      }

      private boolean isCurated_ ;
      /**
       * <code>bool is_curated = 4;</code>
       */
      public boolean getIsCurated() {
        return isCurated_;
      }
      /**
       * <code>bool is_curated = 4;</code>
       */
      public Builder setIsCurated(boolean value) {
        
        isCurated_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool is_curated = 4;</code>
       */
      public Builder clearIsCurated() {
        
        isCurated_ = false;
        onChanged();
        return this;
      }

      private boolean isComputed_ ;
      /**
       * <code>bool is_computed = 5;</code>
       */
      public boolean getIsComputed() {
        return isComputed_;
      }
      /**
       * <code>bool is_computed = 5;</code>
       */
      public Builder setIsComputed(boolean value) {
        
        isComputed_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool is_computed = 5;</code>
       */
      public Builder clearIsComputed() {
        
        isComputed_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:nextprot.PublicationStats)
    }

    // @@protoc_insertion_point(class_scope:nextprot.PublicationStats)
    private static final org.nextprot.stats.publication.PublicationStatistics.PublicationStats DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.nextprot.stats.publication.PublicationStatistics.PublicationStats();
    }

    public static org.nextprot.stats.publication.PublicationStatistics.PublicationStats getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PublicationStats>
        PARSER = new com.google.protobuf.AbstractParser<PublicationStats>() {
      @java.lang.Override
      public PublicationStats parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PublicationStats(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PublicationStats> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PublicationStats> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.nextprot.stats.publication.PublicationStatistics.PublicationStats getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nextprot_PublicationStats_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_nextprot_PublicationStats_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n1src/main/resources/protos/publication-" +
      "stats.proto\022\010nextprot\"q\n\020PublicationStat" +
      "s\022\n\n\002id\030\001 \001(\003\022\020\n\010is_cited\030\002 \001(\010\022\026\n\016is_la" +
      "rge_scale\030\003 \001(\010\022\022\n\nis_curated\030\004 \001(\010\022\023\n\013i" +
      "s_computed\030\005 \001(\010B7\n\036org.nextprot.stats.p" +
      "ublicationB\025PublicationStatisticsb\006proto" +
      "3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_nextprot_PublicationStats_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_nextprot_PublicationStats_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_nextprot_PublicationStats_descriptor,
        new java.lang.String[] { "Id", "IsCited", "IsLargeScale", "IsCurated", "IsComputed", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
